name: Build & Test CI

on: push

jobs:
  build:
    env:
      TZ: America/New_York
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-10
      CXX: g++-10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: sudo apt-get install libcgroup-dev && mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build