name: Build & Test CI

on: push

jobs:
  build:
    env:
      TZ: America/New_York
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-10
      CXX: g++-10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install deps
        run: apt update && apt install -yq software-properties-common && add-apt-repository ppa:ubuntu-toolchain-r/ppa && apt update && apt install -yq cmake python3 gcc-10 g++-10 libcgroup-dev
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build